# CONFIG_BSP_USING_BUILTIN_LCD is not set
CONFIG_RT_MAIN_THREAD_STACK_SIZE=65536
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_DFS_ELM_CODE_PAGE=936
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_LINE_BUF_SIZE=256
# CONFIG_ULOG_USING_COLOR is not set
CONFIG_RT_USING_MEMHEAP=y
CONFIG_RT_USING_MEMTRACE=y
CONFIG_BSP_USING_PM=y
CONFIG_BSP_PM_DEBUG=y
CONFIG_USING_BUTTON_LIB=y
CONFIG_BUTTON_MAX_NUM=3
CONFIG_BUTTON_ADV_ACTION_CHECK_DELAY=1000
CONFIG_USING_BATTERY_CALCULATOR=y
CONFIG_PKG_FREETYPE=y
