# for module compiling
import os
from building import *
import rtconfig

cwd = GetCurrentDir()

src = ['main.cpp','UIRegionsManager.cpp','epub_screen.cpp','epub_mem.c','epub_fonts.c']

src = src + Glob('./assets/*.c') 
CPPPATH = [cwd]

objs = DefineGroup('src', src,depend = [''],CPPPATH = CPPPATH)



list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs = objs + SConscript(os.path.join(cwd, '../waveform/SConscript'))

Return('objs')