from building import * 
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = [cwd]
obj = []
lib = []

if os.path.isfile(os.path.join(cwd, 'epd_waveform_bin_reader_rvds.lib')) or os.path.isfile(os.path.join(cwd, 'libepd_waveform_bin_reader_gcc.a')):
    lib = [GroupLibName("epd_waveform_bin_reader")]
else:
    src = src + Glob('*.c')


obj = DefineGroup('waveform', src, depend = [''], CPPPATH = inc, LIBS=lib, LIBPATH=inc)
Return('obj')
