#!/usr/bin/env python3
"""
Convert waveform xlsx table to C arrays used by te067xjhe01.c style drivers.

Expected sheet layout (same as TM to SHINEVIEW-20250616.xlsx):
- Col B: old gray level (0..15)
- Col C: new gray level (0..15)
- Col D: frame count (usually only first row in each temperature block)
- Col E.. : per-frame waveform values (-15, 0, 15)

Each temperature block uses 256 rows (all old/new combinations), and each block outputs:
- static const uint8_t <array_name>[frame_count][256]
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import openpyxl


DEFAULT_TEMP_RANGES: List[Tuple[int, int, str]] = [
    (0, 5, "0_5"),
    (5, 10, "5_10"),
    (10, 15, "10_15"),
    (15, 20, "15_20"),
    (20, 25, "20_25"),
    (25, 30, "25_30"),
    (30, 35, "30_35"),
    (35, 40, "35_40"),
    (40, 45, "40_45"),
    (45, 50, "45_50"),
    (50, 100, "50_plus"),
]


def parse_value_map(text: str) -> Dict[int, int]:
    """Parse mapping like "-15:2,0:0,15:1"."""
    out: Dict[int, int] = {}
    for part in text.split(","):
        kv = part.strip().split(":")
        if len(kv) != 2:
            raise ValueError(f"Invalid map item: {part}")
        k = int(kv[0].strip())
        v = int(kv[1].strip())
        out[k] = v
    return out


def cell_int(ws, row: int, col: int, default: int | None = None) -> int:
    val = ws.cell(row, col).value
    if val is None:
        if default is None:
            raise ValueError(f"Cell empty at row={row}, col={col}")
        return default
    return int(val)


def extract_block(
    ws,
    start_row: int,
    frame_count: int,
    value_map: Dict[int, int],
) -> List[List[int]]:
    """Build [frame_count][256] for one temperature block."""
    frames = [[0] * 256 for _ in range(frame_count)]

    for row in range(start_row, start_row + 256):
        old_gray = cell_int(ws, row, 2)
        new_gray = cell_int(ws, row, 3)
        idx = old_gray * 16 + new_gray

        if not (0 <= old_gray <= 15 and 0 <= new_gray <= 15):
            raise ValueError(f"Gray level out of range at row={row}: {old_gray}->{new_gray}")

        for f in range(frame_count):
            raw = cell_int(ws, row, 5 + f, default=0)
            if raw not in value_map:
                raise ValueError(
                    f"Unexpected raw waveform value at row={row}, frame={f + 1}: {raw}"
                )
            frames[f][idx] = value_map[raw]

    return frames


def format_array(name: str, frames: List[List[int]]) -> str:
    lines: List[str] = []
    lines.append(f"static const uint8_t {name}[{len(frames)}][256] =")
    lines.append("{")
    for frame in frames:
        row = ",".join(str(v) for v in frame)
        lines.append(f"    {{{row}}},")
    lines.append("};")
    return "\n".join(lines)


def generate_c_text(
    ws,
    prefix: str,
    ranges: List[Tuple[int, int, str]],
    start_row: int,
    frame_count: int,
    value_map: Dict[int, int],
) -> str:
    blocks: List[str] = []
    entries: List[str] = []

    for i, (tmin, tmax, suffix) in enumerate(ranges):
        block_start = start_row + i * 256
        arr_name = f"{prefix}_{suffix}"
        frames = extract_block(ws, block_start, frame_count, value_map)
        blocks.append(format_array(arr_name, frames))
        entries.append(f"    {{{tmin}, {tmax}, {frame_count}, &{arr_name}[0]}},")

    entry_name = f"{prefix}s"
    lines: List[str] = []
    lines.append("/* Auto-generated by tools/waveform_xlsx_to_c.py */")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    int min_temp;")
    lines.append("    int max_temp;")
    lines.append("    uint32_t frame_count;")
    lines.append("    const uint8_t (*wave_table)[256];")
    lines.append("} WaveTableEntry;")
    lines.append("")
    lines.append("\n\n".join(blocks))
    lines.append("")
    lines.append(f"static const WaveTableEntry {entry_name}[] = {{")
    lines.extend(entries)
    lines.append("};")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert waveform xlsx to C arrays")
    parser.add_argument("xlsx", type=Path, help="Input xlsx path")
    parser.add_argument("-o", "--output", type=Path, required=True, help="Output .c/.h text file")
    parser.add_argument("--sheet", default=None, help="Worksheet name, default first sheet")
    parser.add_argument("--prefix", default="te067xjhe_wave_full", help="Array name prefix")
    parser.add_argument(
        "--value-map",
        default="-15:2,0:0,15:1",
        help="Mapping from xlsx values to output values, e.g. -15:2,0:0,15:1",
    )
    parser.add_argument("--start-row", type=int, default=2, help="First data row of first temp block")
    parser.add_argument("--frame-count", type=int, default=45, help="Frame count per temperature block")
    args = parser.parse_args()

    wb = openpyxl.load_workbook(args.xlsx, data_only=True)
    ws = wb[args.sheet] if args.sheet else wb[wb.sheetnames[0]]

    value_map = parse_value_map(args.value_map)
    text = generate_c_text(
        ws=ws,
        prefix=args.prefix,
        ranges=DEFAULT_TEMP_RANGES,
        start_row=args.start_row,
        frame_count=args.frame_count,
        value_map=value_map,
    )

    args.output.write_text(text, encoding="utf-8")
    print(f"Generated: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
